### ISSUE TITLE
Failing the infusion for madmans lense makes the save-file unusable

### ISSUE THREAD

**Issue by Nickodersowas** [Alastors/thaumicinsurgence#24]
When one of the alembics used during the infusion-process of the madmans lense gets turned to flux, the save-file gets corrupted and can't be loaded anymore.

I am using "thaumicinsurgence-0.2.6.jar" which i got from github i think.

I'm also using other addons for Thaumcraft:
- Gadomancy
- Tainted Magic
- Thaumaturgical Knowledge
- Thaumic Bases
- Thaumic Dyes
- Travellers Gear
but i think the crash is tied to Insurgence because i already did a few infusions and it didn't crash.

Hopefully this helps. 

**After the carsh the minecraft launcher displays:**

"The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: bound must be positive"

**Full crash log:**

---- Minecraft Crash Report ----
// My bad.

Time: 20.06.23 19:52
Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.TileInfusionMatrix.craftCycle(TileInfusionMatrix.java:483)
	at thaumcraft.common.tiles.TileInfusionMatrix.func_145845_h(TileInfusionMatrix.java:224)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.TileInfusionMatrix.craftCycle(TileInfusionMatrix.java:483)
	at thaumcraft.common.tiles.TileInfusionMatrix.func_145845_h(TileInfusionMatrix.java:224)

-- Block entity being ticked --
Details:
	Name: TileInfusionStone // thaumcraft.common.tiles.TileInfusionMatrix
	Block type: ID #187 (tile.blockStoneDevice // thaumcraft.common.blocks.BlockStoneDevice)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (191,66,354), Chunk: (at 15,4,2 in 11,22; contains blocks 176,0,352 to 191,255,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #187 (tile.blockStoneDevice // thaumcraft.common.blocks.BlockStoneDevice)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: 1.7.10 Thaumcraft
	All players: 1 total; [EntityPlayerMP['Nickodersowas'/1044911, l='1.7.10 Thaumcraft', x=188,47, y=65,00, z=357,72]]
	Chunk stats: ServerChunkCache: 1275 Drop: 0
	Level seed: 5192489963804796529
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (132,64,256), Chunk: (at 4,4,0 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2109147 game time, 2908139 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 61367 (now: false), thunder time: 68526 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 559470432 bytes (533 MB) / 1207959552 bytes (1152 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAAAAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	TaintedMagic{8.1.1} [Tainted Magic] (Tainted-Magic-1.7.10-8.1.1.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	benway_knowledge{0.1.5.1} [Thaumaturgical Knowledge] (Thaumaturgical Knowledge-0.1.5.2 - 1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	thaumicdyes{1.10.5} [Thaumic Dyes] (Thaumic-Dyes-[1.7.10] 1.10.5-0.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	thaumicinsurgence{0.2.6} [Thaumic Insurgence] (thaumicinsurgence-0.2.6.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Nickodersowas'/1044911, l='1.7.10 Thaumcraft', x=188,47, y=65,00, z=357,72]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Alastors** [comment]
how did the alembic get turned to flux?

**Comment by Alastors** [comment]
OHHHH WAIT, OH THE ALEMBIC IN THE RECIPE

**Comment by Alastors** [comment]
Yeah I'll see if I can recreate it, it honestly might just be a freak accident though, but worst case scenario I might just remove all instability from the recipe itself

**Comment by Alastors** [comment]
> OHHHH WAIT, OH THE ALEMBIC IN THE RECIPE

sorry, I don't always remember my own recipes lmfaoooo

**Comment by Nickodersowas** [comment]
> > OHHHH WAIT, OH THE ALEMBIC IN THE RECIPE
> 
> sorry, I don't always remember my own recipes lmfaoooo

No problem. I can imagine there is a lot to keep track of during mod development. 

Btw, how do i do the thing with the interceptor? The Thaumonomicon just says i should connect tubes to it after i placed it under the central pillar but nothing happens? Even when i start an infusion? And while i'm at it: Are the [hyperlink blocked] fully in the game? They don't seem to do anything other than give a good vis discount and warping.

**Comment by Nickodersowas** [comment]
I generally like how obscure you left everything in the Thaumonomicon entrys and the spamton writing style fits well into that as well, but i think a few more hints as to what to do with the items would be nice.

**Comment by Alastors** [comment]
Thé intercepter really and truly is meant to be used with the essentia provider from Thaumic energistics, you can't really achieve full functionality without it but if you place the intercepter beneath the center pedestal, the bottom face of the intercepter is the pipe-able side that would normally interact with the essentia provider from Thaumic energistics but it should also function with normal thaumcraft piping systems

**Comment by Alastors** [comment]
And no the goggles aren't fully implemented yet, currently they are just another pair of goggles, but they're going to have this sort of cursed item setup eventually

**Comment by Nickodersowas** [comment]
> Thé intercepter really and truly is meant to be used with the essentia provider from Thaumic energistics, you can't really achieve full functionality without it but if you place the intercepter beneath the center pedestal, the bottom face of the intercepter is the pipe-able side that would normally interact with the essentia provider from Thaumic energistics but it should also function with normal thaumcraft piping systems

Ahh, okay. Thanks.

**Comment by Alastors** [comment]
> I generally like how obscure you left everything in the Thaumonomicon entrys and the spamton writing style fits well into that as well, but i think a few more hints as to what to do with the items would be nice.

Yeahhhh, im rewriting the lore currently so it should slowly be easier for the user over time

**Comment by Alastors** [comment]
> > Thé intercepter really and truly is meant to be used with the essentia provider from Thaumic energistics, you can't really achieve full functionality without it but if you place the intercepter beneath the center pedestal, the bottom face of the intercepter is the pipe-able side that would normally interact with the essentia provider from Thaumic energistics but it should also function with normal thaumcraft piping systems
> 
> 
> 
> Ahh, okay. Thanks.

Yeah with Thaumic energistics you can get O(1) infusion essentia handling, or well, 1 tick infusion essentia handling

**Comment by Alastors** [comment]
Though I will say, I'm currently in the process of moving (third time this year 😅) so it might be a week or two before I can fix this issue

**Comment by Nickodersowas** [comment]
> Though I will say, I'm currently in the process of moving (third time this year 😅) so it might be a week or two before I can fix this issue

Sounds stressfull. But yeah, take your time. The mod looks promissing though.

**Comment by Nickodersowas** [comment]
Btw do you have a discord channel for this mod? If the mod gets bigger and more flashed out i could help with a potential german translation if you'd be interested in that.

**Comment by Alastors** [comment]
> Btw do you have a discord channel for this mod? If the mod gets bigger and more flashed out i could help with a potential german translation if you'd be interested in that.

Yeah sort of! I work on the mod as a dev for this 1.7.10 pack called GregTech: New Horizons, though Insurgence is meant to be a standalone mod itself, but I do 99% of my dev work in the #magic-dev channel on their discord!

https://discord.gg/gtnh

**Comment by Alastors** [comment]
I would be very interested in having german translations!

**Comment by Alastors** [comment]
> > Though I will say, I'm currently in the process of moving (third time this year 😅) so it might be a week or two before I can fix this issue
> 
> Sounds stressfull. But yeah, take your time. The mod looks promissing though.

It sure do be, I don't even have a desk right now, so it's rough, I already have the house bought this time, and this is the final move so it should be grand afterwards. 

And thank you! I think so as well!

**Comment by Nickodersowas** [comment]
Sounds like its going well at least. Hopefully everything workes out. 

I joined the discord. My name there is Nickodersowas as well, although i obviously have to see when i have the time to translate because i'm going to start my job training soon. Just write me though if you've got something to translate and i'll see what i can do.

**Comment by Alastors** [comment]
> Sounds like its going well at least. Hopefully everything workes out.
> 
> I joined the discord. My name there is Nickodersowas as well, although i obviously have to see when i have the time to translate because i'm going to start my job training soon. Just write me though if you've got something to translate and i'll see what i can do.

yeah sure no worries! thanks man!
